name: Update Versions

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to use for the extension. Example: 1.5.2'
        required: true

      branch:
        description: 'The target branch where the version update will be applied and the pull request will be merged into.'
        required: true

      core-dependency:
        description: 'If a version is provided, update AEPCore dependency in podspec and Package.swift'
        required: false

      edge-identity-dependency:
        description: 'If a version is provided, update AEPEdgeIdentity dependency in podspec and Package.swift'
        required: false

jobs:
  update-versions:
    uses: timkimadobe/aepsdk-commons/.github/workflows/versions.yml@version-script-update
    with:
      version: ${{ github.event.inputs.version }}
      branch: ${{ github.event.inputs.branch }}
      dependencies: AEPCore ${{ github.event.inputs.core-dependency }}, AEPEdgeIdentity ${{ github.event.inputs.edge-identity-dependency }}
      paths: Package.swift, AEPEdge.podspec, AEPEdge.xcodeproj/project.pbxproj, Sources/EdgeConstants.swift
      # secrets: inherit